### ISSUE TITLE
Does this require an LPC1768 or can I use a Nucleo or other MCUs?

### ISSUE THREAD

**Issue by sofakng** [wesleyivester/YMF262_Player#1]
Does this project require an LPC1768 or can I use another Mbed-supported MCU?

For example, can I use a NUCLEO-F429ZI or NUCLEO-F446RE?

**Comment by wesleyivester** [comment]
Right now this repo contains the code for Mbed OS 2 for LPC1768 so first you would have to move it into whatever you are using to build for NUCLEO. There are a few minor things that use c++11 you might have to change if your compiler doesn't support c++11 (like the online compiler). And I'm not sure if Mbed OS 5 or newer will work without minor changes. But the NUCLEO is definitely capable hardware-wise.

**Comment by sofakng** [comment]
Thanks a bunch for the information!  That's good to hear the NUCLEO is capable so I'll see what I can do to port the code or get it working.
